# data
train_csv: data/train.csv
test_csv: data/test.csv
val_csv: data/val.csv
data_dir: data/

# tasks
tasks: ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Pleural Effusion']
num_classes: 5

arch: "densenet121"
global_pool: "avgmax"

# optmizer
lr: 0.0001
momentum: 0.9
weight_decay: 0.00001

# loader
batch_size: 64
test_batch_size: 64
epochs: 10
num_workers: 8

# train augmentation
scale: 256
rotate_prob: 0.5
rotate_min: -15
rotate_max: 15
contrast_prob: 0.5
contrast_min: 0.5
contrast_max: 1.0
brightness_prob: 0.5
brightness_min: 0.6
brightness_max: 1.0
sharpness_prob: 0.5
sharpness_min: 0.7
sharpness_max: 1.0
horizontal_flip_prob: 0.5
crop: 224 

